### ISSUE TITLE
How to use it properly

### ISSUE THREAD

**Issue by JoepKockelkorn** [retarsis/routerkit#49]
Imagine [in my example repo](https://github.com/JoepKockelkorn/routerkit-paths-bug) that I were to:
- generate another feature, say 'feature-b' also with an overview, 'b-overview' mounted on the root route
- mount 'feature-b' in my app on path 'b'
- and I would generate the routes again using the schematic `nx g @routerkit/core:parse --project app`
- and I then want to point the user from 'a-overview' to 'b-overview' using a routerlink and the generated routes
- and then do the same the other way around, adding a routerlink on 'b-overview' pointing to 'a-overview' using the generated routes

I would then stumble upon two circular dependency issues, as the libs 'feature-a' and 'feature-b' cannot depend on the project 'app' so I cannot use the typings. Even if you would generate the typings for the feature libs and expose them from the lib itself, you would have a circular dependency between libs 'feature-a' and 'feature-b' as they need to reference the generated typings from each other. When not using the generated typings, this pictured scenario is perfectly possible because they are loosely coupled using some 'magic' strings. How will I still be able to use the typings in this setup (monorepo nx style)?

**Comment by JoepKockelkorn** [comment]
Extra visualisation (don't mind the ui libs, they are redundant to describe this issue).

Without using the typings there are no issues:
<img src="https://user-images.githubusercontent.com/12891645/93995359-320cb400-fd91-11ea-82c4-97859e7f6eab.png" width="400" />

When using the typings, there are circular dependencies (red arrows):
<img src="https://user-images.githubusercontent.com/12891645/93995397-3e910c80-fd91-11ea-9344-da927e28f7b0.png" width="400" />

**Comment by retarsis** [comment]
oh, it's weird

because types file should be a separate unit which only imports 1 thing file from node_modules/@routerkit/core and always exports the type...

can you add a commit to reproduce circular dependencies in your [example repo](https://github.com/JoepKockelkorn/routerkit-paths-bug)?

**Comment by JoepKockelkorn** [comment]
@retarsis Sure, [it's this commit](https://github.com/JoepKockelkorn/routerkit-paths-bug/commit/483420fdb3242aaa167dab74c566b896c8825a38). When you open up [a-overview.component.ts](https://github.com/JoepKockelkorn/routerkit-paths-bug/blob/master/libs/feature-a/src/lib/a-overview/a-overview.component.ts) in VSCode, the nx linting rule will tell you about the circular dependency.

### The problem in detail
In a monorepo setup like nx, features (libs) can be reused in multiple apps and don't know anything about the app they're used in. So storing the generated typings on app level is not going to work in my depicted scenario: if you want to use a route path of a feature in another feature and vice versa.

On the other hand, storing the routes in the feature lib itself also won't work as this can introduce circular dependencies as I explained in the example above. So I don't see any other solution than storing the route typings in a separate lib with no reference to the feature lib (to keep it loosely coupled). So the feature lib and all other features/apps can use the generated routes without introducing circular dependencies. This introduces a small problem: the generated routes typings can get out of sync with its source. 

In the project I'm working on right now, we just have a separate lib with all routes/magic strings and use this lib in both the components (for routerLinks) and in modules for the routing declaration. This has also the downside of this lib sometimes not being used and the lib with the routes being out of sync with the reality.

### Sidetrack
While preparing this comment, I also came across a bug regarding lazy loaded modules and empty paths. The types are not correct for those. They are called 'root' while they're just an empty string. When you use those with the routerLink directive they obviously won't work because there is no route with a 'root' path. The correct route path is an empty string.

**Comment by retarsis** [comment]
@JoepKockelkorn i'll answer for sidetracks

That is a design for empty paths to be `root`.
I didn't think it's unclear for new users, but ok, I'll think more about it

```typescript
    location: {
        root: TypedRoute<[
            '/',
            'location'
        ]>;
  }
```

as you can see, location has a property `root` but the final tuple hasn't `root` path

sorry for this, I'll take some time to brainstorm this, otherwise I'll add additional documentation about this

does it makes sense? did my answer help?

**Comment by JoepKockelkorn** [comment]
I think I then stumbled upon a bug in the `getRoutes` function because I can see that 'root' is in the actual rendered href and the routing in my minimal example repo therefore doesn't work. The href of the link on the `a-overview` is `http://localhost:4200/b/root` where it should be `http://localhost:4200/b`. The typing is correct though.

Btw, I get the way you intended it now. The idea is quite okay 😄 but it might clash when the dev actually has a route named 'root'. It might be more dev friendly if `routes.b` would also have the `asString`, `asArray` and `toString` methods instead of having to do `.root`, but I don't know the consequences of that.

**Comment by retarsis** [comment]
1) `root` inside **href** is a bug

2)now I am actively thinking about the options for renaming the root. Current options: `ROOT` and `EMPTY`.
Not quite satisfied yet, I will make a decision in the near future

3) we apply `root` only if particular route has siblings

**Good**
```javascript
{
    location: {
        root: TypedRoute<[
            '/',
            'location'
        ]>;

       map: TypedRoute<[
            '/',
            'location',
            'map'
        ]>;
    }
}
```
**Bad**
```javascript
{
    location: {
        root: TypedRoute<[
            '/',
            'location'
        ]>;

       map: TypedRoute<[
            '/',
            'location',
            'map'
        ]>;
    }
}
```

If route has no siblings, then it will be structured in that way:

```javascript
```javascript
{
    location: TypedRoute<[ '/', 'location']>;
}
```
```

**Comment by JoepKockelkorn** [comment]
@retarsis Yes it's available in my repo. Just navigate to `localhost:4200/a` after `yarn ng serve` and the link to b-overview has 'root' in it.

**Comment by retarsis** [comment]
@JoepKockelkorn thanks a lot, again 😅

I will come back to this issue tomorrow as there is a lot of other work to be done.

**Comment by retarsis** [comment]
So, both issues are identified and I started working on it.

**Comment by retarsis** [comment]
@JoepKockelkorn I have news

The fix is in `master` branch for both issues but I didn't release it because we have few issues to fix with `parser`. I think we will release this in a few days.

sorry for keeping you waiting

but there is more good news
I added you as a contributor to the project because I appreciate what you have done for the project

**Comment by JoepKockelkorn** [comment]
@retarsis Nice, thanks! Regarding the waiting, no problem as I don't use it yet. I have to figure out how in a nx setup.

**Comment by retarsis** [comment]
@JoepKockelkorn about nx repo issue I decided to just generate `routes type` file in the `rootDir` because "circular dependency" isn't real (project compiles and only custom lint rule complains). It's just a custom lint rule from `nx` team when you import anything in the not appropriate way (from `app` to `feature` and from `feature` to `app`).

**Comment by JoepKockelkorn** [comment]
> about nx repo issue I decided to just generate routes type file in the rootDir because "circular dependency" isn't real (project compiles and only custom lint rule complains)

How is the circular dependency not real? Even though they're just typings, it's definitely a reference in both ways.

> and starting from the next release you generated files will be located in the rootDir which means you won't have circular dependencies anymore

So what happens if you have two apps and you generate the typings for both of them?

**Comment by retarsis** [comment]
> How is the circular dependency not real? Even though they're just typings, it's definitely a reference in both ways.

if I'm not mistaken typescript destroys types on compilation
by the way, `routes type` file doesn't import anything except `TypedRoute` from node_modules that's why you won't have circularity anyway. Custom lint rule from `nx` is just a semantic thing to warn.

> So what happens if you have two apps and you generate the typings for both of them?

Each generated `routes type` file has unique project name (you can't have 2 different apps with the same project name)
Let's suppose you have 2 apps with the following names: `app1` and `app2`.
The output of `routerkit` will be `app1.routes.d.ts.` and `app2.routes.d.ts` in the root folder.

**Comment by retarsis** [comment]
@JoepKockelkorn just released **0.8.0**, check it out

https://github.com/retarsis/routerkit/releases/tag/0.8.0

**Comment by JoepKockelkorn** [comment]
@retarsis Looking good, nice to see my comments being taken seriously. However, I'm not convinced of the `rootDir` approach. Referencing the typed routes of a feature module though the generated routes of an app feels dirty, even though it's just typings and will not be bundled in the resulting deployable bundles.

If this package would have the following features then the devs can decide for themselves how to use it properly:
- Besides generating routes of an app, the tool allows to generate typed routes of a lazy loaded feature module separately
- Be able to pass a param/config path where to write the generated typings

If this tool would have these options I would use it as following in a nx repo:
1. Generate separate sibling libs for all my lazy loaded feature libs where all of the typed routings are going to live
2. Generate the typings using this tool into the generated libs so it can be used (imported) it other features while keeping the loosely coupled characteristic

Generating the typed routings of a feature module is currently not possible as it throws this error:
`Can't find tsconfig inside angular.json for feature-a project. An appropriate config name should include 'tsconfig' and '.json'`. I don't know if it even is possible, haven't investigated.

**Comment by retarsis** [comment]
@JoepKockelkorn I do appreciate your efforts, therefore we try to help in response

You say interesting ideas, but meanwhile, they are not quite included in the project plans for the 1.0.0 release, and I want to spend time improving the parser and other basic features that are necessary for the 1.0.0 release.

What you propose sounds interesting, and it really makes sense, since I already had experience with workspaces.
But the problem is that we will have to rewrite many things and this will take a significant amount of time.

Therefore, in order not to miss anything, and to separate the problem from the request, I propose to proceed as follows:
- close this issue as we have resolved several issues related to the original issue
- create RFC through a new issue item, and describe exactly what is not ok and how it should work
- attach a link with this issue to the newly created

@JoepKockelkorn does that suit you?

**Comment by JoepKockelkorn** [comment]
@retarsis Yeah of course! My priority is not yours, I understand that completely 🙂

**Comment by JoepKockelkorn** [comment]
Closing this issue, created an RFC #73
